### ISSUE TITLE
D3/underscore dependencies (docs)

### ISSUE THREAD

**Issue by nwolverson** [pleasetrythisathome/react.animate#19]
Instructions mention D3 and underscore as dependencies and discusses limitations of D3 transitions but they don't seem to be dependencies.

**Comment by pleasetrythisathome** [comment]
fixed, thanks for the catch!

**Comment by nwolverson** [comment]
Still don't understand, is d3 involved somehow or not? 

The example code - does that just use d3 to illustrate the idea assuming the reader is familiar with D3? (Fine but I'd call it out.)

Bottom of the README: "Due to the nature of d3's transition system, starting a new animation on a component will cancel the current running animation." What has D3 got to do with it?

**Comment by pleasetrythisathome** [comment]
removed all references to d3. d3 was used in the initial implementation and those limitations have been removed. references to d3 were stale. sorry for the confusion

**Comment by nwolverson** [comment]
Looks good to me now! Cheers :+1:

**Comment by adabru** [comment]
There is still the Underscore dependency mentioned in the Readme although it was also removed. A change of the Readme and an update of the npm-package (the version there still depends on underscore) would be nice.
